apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        joshyunho/golang-test: true
        joshyunho/jx3-k8s-3: true
        joshyunho/rust-http: true
        joshyunho/vertx-rest-prometheus: true
        joshyunho/vertx-rest-prometheus2: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        joshyunho/golang-test: merge
        joshyunho/jx3-k8s-3: merge
        joshyunho/rust-http: merge
        joshyunho/vertx-rest-prometheus: merge
        joshyunho/vertx-rest-prometheus2: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - joshyunho/jx3-k8s-3
        - joshyunho/golang-test
        - joshyunho/rust-http
        - joshyunho/vertx-rest-prometheus
        - joshyunho/vertx-rest-prometheus2
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - joshyunho/jx3-k8s-3
        - joshyunho/golang-test
        - joshyunho/rust-http
        - joshyunho/vertx-rest-prometheus
        - joshyunho/vertx-rest-prometheus2
      target_url: http://lighthouse-jx.207.192.68.193.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
